// Device-local support-chat history (client-only). Persists the messages array
// AND a per-conversation external_key to localStorage so a swiped-out / closed
// chat reopens where it left off, and so the server can correlate every ingested
// transcript back to one durable conversation id.
//
// Keyed per audience + a hash of the caller's stable identifier (the student's
// token, or the business user id). We store ONLY the SHA-256 hash of that
// identifier — never the raw auth token — so the storage key can't be turned
// back into a credential. The server stays stateless; this is purely a local
// convenience.
//
// The external_key shares the history's lifecycle: it is restored on mount,
// regenerated by "Start new conversation" (via a fresh key + cleared storage),
// and regenerated on the 7-day expiry (expired storage is dropped and load
// returns a new key).

export type StoredMsg = { role: "user" | "assistant"; content: string }
export type Conversation = { messages: StoredMsg[]; externalKey: string }

const PREFIX = "bizzy_support_chat:v1"
const EXPIRY_MS = 7 * 24 * 60 * 60 * 1000 // 7 days
// Cap stored turns; matches the server's MAX_TURNS so we never persist more
// than a conversation is allowed to carry.
export const HISTORY_CAP = 40

// Tiny non-crypto fallback for the (unlikely) case SubtleCrypto is unavailable
// — still one-way, still never the raw token.
function djb2(input: string): string {
  let h = 5381
  for (let i = 0; i < input.length; i++) h = (h * 33) ^ input.charCodeAt(i)
  return (h >>> 0).toString(16)
}

/** A fresh conversation id (UUID). One per conversation; never derived from auth. */
export function newExternalKey(): string {
  try {
    if (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function")
      return crypto.randomUUID()
  } catch {
    // fall through to the manual constructions below
  }
  try {
    const b = new Uint8Array(16)
    crypto.getRandomValues(b)
    b[6] = (b[6] & 0x0f) | 0x40 // version 4
    b[8] = (b[8] & 0x3f) | 0x80 // variant
    const h = Array.from(b)
      .map((x) => x.toString(16).padStart(2, "0"))
      .join("")
    return `${h.slice(0, 8)}-${h.slice(8, 12)}-${h.slice(12, 16)}-${h.slice(16, 20)}-${h.slice(20)}`
  } catch {
    // Last-resort non-crypto id; uniqueness is best-effort at this point.
    return `ek-${Date.now().toString(16)}-${djb2(String(Math.random()))}`
  }
}

/** Build the localStorage key from the audience + a one-way hash of the seed. */
export async function historyKey(audience: string, seed: string): Promise<string> {
  const material = `${audience}:${seed}`
  let hash: string
  try {
    const data = new TextEncoder().encode(material)
    const digest = await crypto.subtle.digest("SHA-256", data)
    hash = Array.from(new Uint8Array(digest))
      .map((b) => b.toString(16).padStart(2, "0"))
      .join("")
      .slice(0, 32)
  } catch {
    hash = djb2(material)
  }
  return `${PREFIX}:${audience}:${hash}`
}

function isMsg(m: unknown): m is StoredMsg {
  const r = (m as StoredMsg)?.role
  return (r === "user" || r === "assistant") && typeof (m as StoredMsg)?.content === "string"
}

/**
 * Load the stored conversation for a key, honouring the 7-day expiry and the
 * cap. Always returns an externalKey — the stored one for a live conversation,
 * or a freshly minted one for an empty / expired / absent conversation.
 */
export function loadConversation(key: string): Conversation {
  if (typeof window === "undefined") return { messages: [], externalKey: newExternalKey() }
  try {
    const raw = window.localStorage.getItem(key)
    if (!raw) return { messages: [], externalKey: newExternalKey() }
    const parsed = JSON.parse(raw) as {
      ts?: unknown
      messages?: unknown
      external_key?: unknown
    }
    if (typeof parsed?.ts !== "number" || !Array.isArray(parsed.messages))
      return { messages: [], externalKey: newExternalKey() }
    if (Date.now() - parsed.ts > EXPIRY_MS) {
      // Expiry regenerates the conversation: drop storage, hand back a new key.
      window.localStorage.removeItem(key)
      return { messages: [], externalKey: newExternalKey() }
    }
    const messages = parsed.messages.filter(isMsg).slice(-HISTORY_CAP)
    const externalKey =
      typeof parsed.external_key === "string" && parsed.external_key
        ? parsed.external_key
        : newExternalKey() // pre-external_key records: mint one, persisted on next save
    return { messages, externalKey }
  } catch {
    return { messages: [], externalKey: newExternalKey() }
  }
}

/** Persist messages (capped to the last HISTORY_CAP turns) + the conversation key. */
export function saveConversation(
  key: string,
  messages: StoredMsg[],
  externalKey: string,
): void {
  if (typeof window === "undefined") return
  try {
    window.localStorage.setItem(
      key,
      JSON.stringify({
        v: 1,
        ts: Date.now(),
        external_key: externalKey,
        messages: messages.slice(-HISTORY_CAP),
      }),
    )
  } catch {
    // Quota / private-mode failures are non-fatal — history is best-effort.
  }
}

/** Clear a conversation ("Start new conversation"). */
export function clearHistory(key: string): void {
  if (typeof window === "undefined") return
  try {
    window.localStorage.removeItem(key)
  } catch {
    // ignore
  }
}
